In [1]:
# scrollable plots
%matplotlib notebook

# # simple plots
# %matplotlib inline

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as sig
import importlib

try:
    importlib.reload(mtools)
except NameError:
    import mixing_tools as mtools

## Testing unit functions

In [24]:
# create samples for testing out import functions

def create_sample_int16():
    x = np.arange(1,10+1, dtype=np.int16)
    x.tofile('test-int16.bin')
create_sample_int16()

def create_sample_float64():
    x = np.arange(11,20+1, dtype=np.float64)
    x.tofile('test-float64.bin')
create_sample_float64()

In [16]:
# testing out frequency <-> FFT index functions

# sample 1: basic operation with even sized FFTs
fs = 32
ts = 1/fs
n = 16
f1 = np.fft.fftfreq(n, d=ts)
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')

print("fpos {}: floor index {}, {}".format(7.0, *mtools.fpos2indFloor(7.0, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(7.0, *mtools.fpos2indCeil(7.0, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(8.1, *mtools.fpos2indFloor(8.1, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(8.1, *mtools.fpos2indCeil(8.1, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(-7.0, *mtools.fneg2indFloor(-7.0, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(-7.0, *mtools.fneg2indCeil(-7.0, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(-8.0, *mtools.fneg2indFloor(-8.0, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(-8.0, *mtools.fneg2indCeil(-8.0, n, ts, fout=True)))
print()

# sample 2: test out working with FFTs with odd number of elements
fs = 27
ts = 1/fs
n = 15
f1 = np.fft.fftfreq(n, d=ts)
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')

print("fpos {}: floor index {}, {}".format(7.0, *mtools.fpos2indFloor(7.0, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(7.0, *mtools.fpos2indCeil(7.0, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(8.1, *mtools.fpos2indFloor(8.1, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(8.1, *mtools.fpos2indCeil(8.1, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(-7.0, *mtools.fneg2indFloor(-7.0, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(-7.0, *mtools.fneg2indCeil(-7.0, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(-8.0, *mtools.fneg2indFloor(-8.0, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(-8.0, *mtools.fneg2indCeil(-8.0, n, ts, fout=True)))
print()

# sample 3: test out center frequency offset
fs = 32
ts = 1/fs
n = 16
fc = 31
f1 = np.fft.fftfreq(n, d=ts)
f1[0:8] = f1[0:8] + fc
f1[8:] = f1[8:] - fc
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')

print("fpos {}: floor index {}, {}".format(7.0, *mtools.fpos2indFloor(7.0 + fc, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(7.0, *mtools.fpos2indCeil(7.0 + fc, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(8.1, *mtools.fpos2indFloor(8.1 + fc, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(8.1, *mtools.fpos2indCeil(8.1 + fc, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(-7.0, *mtools.fneg2indFloor(-7.0 -fc, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(-7.0, *mtools.fneg2indCeil(-7.0 - fc, n, ts, fout=True)))

print("fpos {}: floor index {}, {}".format(-8.0, *mtools.fneg2indFloor(-8.0 - fc, n, ts, fout=True)))
print("fpos {}: ceil index {}, {}".format(-8.0, *mtools.fneg2indCeil(-8.0 - fc, n, ts, fout=True)))

ind, f1:
(0, 0.0)
(1, 2.0)
(2, 4.0)
(3, 6.0)
(4, 8.0)
(5, 10.0)
(6, 12.0)
(7, 14.0)
(8, -16.0)
(9, -14.0)
(10, -12.0)
(11, -10.0)
(12, -8.0)
(13, -6.0)
(14, -4.0)
(15, -2.0)
fpos 7.0: floor index 3, 6.0
fpos 7.0: ceil index 4, 8.0
fpos 8.1: floor index 4, 8.0
fpos 8.1: ceil index 5, 10.0
fpos -7.0: floor index 12, -8.0
fpos -7.0: ceil index 13, -6.0
fpos -8.0: floor index 12, -8.0
fpos -8.0: ceil index 12, -8.0

ind, f1:
(0, 0.0)
(1, 1.7999999999999998)
(2, 3.5999999999999996)
(3, 5.3999999999999995)
(4, 7.199999999999999)
(5, 9.0)
(6, 10.799999999999999)
(7, 12.599999999999998)
(8, -12.599999999999998)
(9, -10.799999999999999)
(10, -9.0)
(11, -7.199999999999999)
(12, -5.3999999999999995)
(13, -3.5999999999999996)
(14, -1.7999999999999998)
fpos 7.0: floor index 3, 5.4
fpos 7.0: ceil index 4, 7.2
fpos 8.1: floor index 4, 7.2
fpos 8.1: ceil index 5, 9.0
fpos -7.0: floor index 11, -7.2
fpos -7.0: ceil index 12, -5.4
fpos -8.0: floor index 10, -9.0
fpos -8.0: ceil index 11, -7.2

ind, f1:


In [15]:
# sample 1: basic operation with even sized FFTs
fs = 32
ts = 1/fs
n = 16
f1 = np.fft.fftfreq(n, d=ts)
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')
fftShifted = mtools.fft_basebandShift(f1, 2, 5)
print("size:", fftShifted.size)
print(fftShifted)
print()

# sample 2: off sized series
fs = 27
ts = 1/fs
n = 15
f1 = np.fft.fftfreq(n, d=ts)
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')
fftShifted = mtools.fft_basebandShift(f1, 0, 2)
print("size:", fftShifted.size)
print(fftShifted)
print()

ind, f1:
(0, 0.0)
(1, 2.0)
(2, 4.0)
(3, 6.0)
(4, 8.0)
(5, 10.0)
(6, 12.0)
(7, 14.0)
(8, -16.0)
(9, -14.0)
(10, -12.0)
(11, -10.0)
(12, -8.0)
(13, -6.0)
(14, -4.0)
(15, -2.0)
size: 6
[  4.   6.   8. -10.  -8.  -6.]

ind, f1:
(0, 0.0)
(1, 1.7999999999999998)
(2, 3.5999999999999996)
(3, 5.3999999999999995)
(4, 7.199999999999999)
(5, 9.0)
(6, 10.799999999999999)
(7, 12.599999999999998)
(8, -12.599999999999998)
(9, -10.799999999999999)
(10, -9.0)
(11, -7.199999999999999)
(12, -5.3999999999999995)
(13, -3.5999999999999996)
(14, -1.7999999999999998)
size: 4
[ 0.   1.8 -3.6 -1.8]



In [19]:
# given a data series recorded at sampling intervals Ts and center frequency fcData,
# return a new data series with only data in a certain bandwidth around or after fcSignal
def basebandShift(data, Ts, bwSignal, fcSignal=0.0, fcData=0.0, signalType='ss'):
    n = data.size
    fdata = np.fft.fft(data)
    if signalType == 'ss':
        # signal is single sided
        fStart = fcSignal
        fEnd = fcSignal + bwSignal
    elif signalType == 'ds':
        # signal is double sided
        fStart = fcSignal - bwSignal/2
        fEnd = fcSignal + bwSignal/2
    # TODO: check 
    indStart, f0 = mtools.fpos2indFloor(fStart, n, Ts, fcData=0, fout=True)
    indEnd = mtools.fpos2indCeil(fEnd, n, Ts, fcData=0, fout=False)
    dataShifted = mtools.fft_basebandShift(fdata, indStart, indEnd+1)
    return dataShifted, f0, TsShifted

140625.0


In [70]:
def fft_basebandShift_singleSided(fftdata, indStart, nBuckets):
    n = fftdata.size
    # fbb = np.zeros(2*nBuckets)
    # fbb[0:nBuckets] = fftdata[indStart:(indStart+nBuckets)]
    # fbb[nBuckets:] = fftdata[(n-(indStart+nBuckets)):(n-indStart)]
    fbb = np.concatenate((fftdata[indStart:(indStart+nBuckets)],
                          fftdata[(n-(indStart+nBuckets)):(n-indStart)]))
    return fbb

f = np.fft.fftfreq(16, 1/16)
print(f)
print(fft_basebandShift_singleSided(f, 5, 3))
print()

f = np.fft.fftfreq(15, 1/15)
print(f)
print(fft_basebandShift_singleSided(f, 5, 3))

[ 0.  1.  2.  3.  4.  5.  6.  7. -8. -7. -6. -5. -4. -3. -2. -1.]
[ 5.  6.  7. -8. -7. -6.]

[ 0.  1.  2.  3.  4.  5.  6.  7. -7. -6. -5. -4. -3. -2. -1.]
[ 5.  6.  7.  7. -7. -6.]


In [71]:
def fft_basebandShift_bucketCenter(fftdata, indCenter, nBuckets):
    n = fftdata.size

15


In [30]:
# get relevant fft indices for a signal 
def fftIndices(n, fcData, TsData, fcSignal, bwSignal):
    fBuckets = np.fft.fftfreq(n, TsData)
    
    fStart = fcSignal - bwSignal/2
    fEnd = fcSignal + bwSignal/2
    print("fStart: {}, fEnd: {}".format(fStart, fEnd))
    
    
    
    ipStart = 0
    ipEnd = 0
    inStart = 0
    inEnd = 0
    return (ipStart, ipEnd, inStart, inEnd)

(ipStart, ipEnd, inStart, inEnd) = fftIndices(f1.size, 0, ts, 7, 3)

ind, f1:
(0, 0.0)
(1, 2.0)
(2, 4.0)
(3, 6.0)
(4, 8.0)
(5, 10.0)
(6, 12.0)
(7, 14.0)
(8, -16.0)
(9, -14.0)
(10, -12.0)
(11, -10.0)
(12, -8.0)
(13, -6.0)
(14, -4.0)
(15, -2.0)
fpos 7.0: floor index 3
fpos 7.0: ceil index 4
fpos 8.1: floor index 4
fpos 8.1: ceil index 5
fpos -7.0: floor index 12
fpos -7.0: ceil index 13
fpos -8.0: floor index 12
fpos -8.0: ceil index 12
ind, f1:
(0, 0.0)
(1, 1.7999999999999998)
(2, 3.5999999999999996)
(3, 5.3999999999999995)
(4, 7.199999999999999)
(5, 9.0)
(6, 10.799999999999999)
(7, 12.599999999999998)
(8, -12.599999999999998)
(9, -10.799999999999999)
(10, -9.0)
(11, -7.199999999999999)
(12, -5.3999999999999995)
(13, -3.5999999999999996)
(14, -1.7999999999999998)
fpos 7.0: floor index 3
fpos 7.0: ceil index 4
fpos 8.1: floor index 4
fpos 8.1: ceil index 5
fpos -7.0: floor index 11
fpos -7.0: ceil index 12
fpos -8.0: floor index 10
fpos -8.0: ceil index 11
ind, f1:
(0, 31.0)
(1, 33.0)
(2, 35.0)
(3, 37.0)
(4, 39.0)
(5, 41.0)
(6, 43.0)
(7, 45.0)
(8, -47.0)
