In [1]:
%matplotlib notebook

In [3]:
import importlib
try:
    importlib.reload(mtools)
except NameError:
    import mixing_tools as mtools

In [5]:
mtools.matchedFilter(1, 2)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as sig

In [24]:
def create_sample_int16():
    x = np.arange(1,10+1, dtype=np.int16)
    x.tofile('test-int16.bin')
    
# create_sample_int16()

def create_sample_float64():
    x = np.arange(11,20+1, dtype=np.float64)
    x.tofile('test-float64.bin')
    
# create_sample_float64()

In [23]:
# data import functions

def load_IQBinary_float32(file):
    # I and Q are both 32 bit floats
    return np.fromfile(file, dtype=np.complex64)

def load_IQBinary_float64(file):
    # I and Q are both 32 bit floats
    return np.fromfile(file, dtype=np.complex128)

def load_IQBinary_int8(file):
    # I and Q are both 8 bit ints
    x = np.fromfile(file, dtype=np.int8)
    x = x[0::2] + 1j*x[1::2]
    return x.astype('complex64')

def load_IQBinary_int16(file):
    # I and Q are both 16 bit ints
    x = np.fromfile(file, dtype=np.int16)
    x = x[0::2] + 1j*x[1::2]
    return x.astype('complex64')

xf = load_IQBinary_float64("test-float64.bin")
print(xf)
xi = load_IQBinary_int16("test-int16.bin")
print(xi)

[11.+12.j 13.+14.j 15.+16.j 17.+18.j 19.+20.j]
[1. +2.j 3. +4.j 5. +6.j 7. +8.j 9.+10.j]


In [70]:
def fft_basebandShift_singleSided(fftdata, indStart, nBuckets):
    n = fftdata.size
    # fbb = np.zeros(2*nBuckets)
    # fbb[0:nBuckets] = fftdata[indStart:(indStart+nBuckets)]
    # fbb[nBuckets:] = fftdata[(n-(indStart+nBuckets)):(n-indStart)]
    fbb = np.concatenate((fftdata[indStart:(indStart+nBuckets)],
                          fftdata[(n-(indStart+nBuckets)):(n-indStart)]))
    return fbb

f = np.fft.fftfreq(16, 1/16)
print(f)
print(fft_basebandShift_singleSided(f, 5, 3))
print()

f = np.fft.fftfreq(15, 1/15)
print(f)
print(fft_basebandShift_singleSided(f, 5, 3))

[ 0.  1.  2.  3.  4.  5.  6.  7. -8. -7. -6. -5. -4. -3. -2. -1.]
[ 5.  6.  7. -8. -7. -6.]

[ 0.  1.  2.  3.  4.  5.  6.  7. -7. -6. -5. -4. -3. -2. -1.]
[ 5.  6.  7.  7. -7. -6.]


In [71]:
def fft_basebandShift_bucketCenter(fftdata, indCenter, nBuckets):
    n = fftdata.size

15


In [ ]:
import numpy as np
import scipy.signal as sig



In [30]:
import numpy as np

# TODO: add use of fc
def fpos2indFloor(f, n, Ts, fc=0):
    return int(np.floor(np.round(n*(f-fc)*Ts, 3)))


def fpos2indCeil(f, n, Ts, fc=0):
    return int(np.ceil(np.round(n*(f-fc)*Ts, 3)))


def fneg2indFloor(f, n, Ts, fc=0):
    return int(n + np.floor(np.round(n*(f+fc)*Ts, 3)))


def fneg2indCeil(f, n, Ts, fc=0):
    return int(n + np.ceil(np.round(n*(f+fc)*Ts, 3)))


# sample 1
fs = 32
ts = 1/fs
f1 = np.fft.fftfreq(16, d=ts)
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')

print("fpos {}: floor index {}".format(7.0, fpos2indFloor(7.0, 16, ts)))
print("fpos {}: ceil index {}".format(7.0, fpos2indCeil(7.0, 16, ts)))

print("fpos {}: floor index {}".format(8.1, fpos2indFloor(8.1, 16, ts)))
print("fpos {}: ceil index {}".format(8.1, fpos2indCeil(8.1, 16, ts)))

print("fpos {}: floor index {}".format(-7.0, fneg2indFloor(-7.0, 16, ts)))
print("fpos {}: ceil index {}".format(-7.0, fneg2indCeil(-7.0, 16, ts)))

print("fpos {}: floor index {}".format(-8.0, fneg2indFloor(-8.0, 16, ts)))
print("fpos {}: ceil index {}".format(-8.0, fneg2indCeil(-8.0, 16, ts)))

# sample 2
fs = 27
ts = 1/fs
f1 = np.fft.fftfreq(15, d=ts)
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')

print("fpos {}: floor index {}".format(7.0, fpos2indFloor(7.0, 15, ts)))
print("fpos {}: ceil index {}".format(7.0, fpos2indCeil(7.0, 15, ts)))

print("fpos {}: floor index {}".format(8.1, fpos2indFloor(8.1, 15, ts)))
print("fpos {}: ceil index {}".format(8.1, fpos2indCeil(8.1, 15, ts)))

print("fpos {}: floor index {}".format(-7.0, fneg2indFloor(-7.0, 15, ts)))
print("fpos {}: ceil index {}".format(-7.0, fneg2indCeil(-7.0, 15, ts)))

print("fpos {}: floor index {}".format(-8.0, fneg2indFloor(-8.0, 15, ts)))
print("fpos {}: ceil index {}".format(-8.0, fneg2indCeil(-8.0, 15, ts)))


# sample 3
fs = 32
ts = 1/fs
fc = 31
f1 = np.fft.fftfreq(16, d=ts)
f1[0:8] = f1[0:8] + fc
f1[8:] = f1[8:] - fc
print("ind, f1:", *[(x,f) for x,f in enumerate(f1)], sep='\n')

print("fpos {}: floor index {}".format(7.0+fc, fpos2indFloor(7.0+fc, 16, ts, fc)))
print("fpos {}: ceil index {}".format(7.0+fc, fpos2indCeil(7.0+fc, 16, ts, fc)))

print("fpos {}: floor index {}".format(8.1+fc, fpos2indFloor(8.1+fc, 16, ts, fc)))
print("fpos {}: ceil index {}".format(8.1+fc, fpos2indCeil(8.1+fc, 16, ts, fc)))

print("fpos {}: floor index {}".format(-7.0-fc, fneg2indFloor(-7.0-fc, 16, ts, fc)))
print("fpos {}: ceil index {}".format(-7.0-fc, fneg2indCeil(-7.0-fc, 16, ts, fc)))

print("fpos {}: floor index {}".format(-8.0-fc, fneg2indFloor(-8.0-fc, 16, ts, fc)))
print("fpos {}: ceil index {}".format(-8.0-fc, fneg2indCeil(-8.0-fc, 16, ts, fc)))

# get relevant fft indices for a signal 
def fftIndices(n, fcData, TsData, fcSignal, bwSignal):
    fBuckets = np.fft.fftfreq(n, TsData)
    
    fStart = fcSignal - bwSignal/2
    fEnd = fcSignal + bwSignal/2
    print("fStart: {}, fEnd: {}".format(fStart, fEnd))
    
    
    
    ipStart = 0
    ipEnd = 0
    inStart = 0
    inEnd = 0
    return (ipStart, ipEnd, inStart, inEnd)

(ipStart, ipEnd, inStart, inEnd) = fftIndices(f1.size, 0, ts, 7, 3)

ind, f1:
(0, 0.0)
(1, 2.0)
(2, 4.0)
(3, 6.0)
(4, 8.0)
(5, 10.0)
(6, 12.0)
(7, 14.0)
(8, -16.0)
(9, -14.0)
(10, -12.0)
(11, -10.0)
(12, -8.0)
(13, -6.0)
(14, -4.0)
(15, -2.0)
fpos 7.0: floor index 3
fpos 7.0: ceil index 4
fpos 8.1: floor index 4
fpos 8.1: ceil index 5
fpos -7.0: floor index 12
fpos -7.0: ceil index 13
fpos -8.0: floor index 12
fpos -8.0: ceil index 12
ind, f1:
(0, 0.0)
(1, 1.7999999999999998)
(2, 3.5999999999999996)
(3, 5.3999999999999995)
(4, 7.199999999999999)
(5, 9.0)
(6, 10.799999999999999)
(7, 12.599999999999998)
(8, -12.599999999999998)
(9, -10.799999999999999)
(10, -9.0)
(11, -7.199999999999999)
(12, -5.3999999999999995)
(13, -3.5999999999999996)
(14, -1.7999999999999998)
fpos 7.0: floor index 3
fpos 7.0: ceil index 4
fpos 8.1: floor index 4
fpos 8.1: ceil index 5
fpos -7.0: floor index 11
fpos -7.0: ceil index 12
fpos -8.0: floor index 10
fpos -8.0: ceil index 11
ind, f1:
(0, 31.0)
(1, 33.0)
(2, 35.0)
(3, 37.0)
(4, 39.0)
(5, 41.0)
(6, 43.0)
(7, 45.0)
(8, -47.0)


In [24]:
np.round(2.001, 2)

2.0